export const ALL_PRODUCTS_REQUEST ='ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS ='ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL ='ALL_PRODUCTS_FAIL'

export const PRODCUCT_DETAIL_REQUEST = 'PRODCUCT_DETAIL_REQUEST'
export const PRODCUCT_DETAIL_SUCCESS = 'PRODCUCT_DETAIL_SUCCESS'
export const PRODCUCT_DETAIL_FAIL = 'PRODCUCT_DETAIL_FAIL'


export const CLEAR_ERRORS ='CLEAR_ERRORS'